

#define BAR_WINDOW_OPEN_TOP_X
#define BAR_WINDOW_OPEN_TOP_Y

#define BAR_WINDOW_OPEN_MIDDLE_X
#define BAR_WINDOW_OPEN_MIDDLE_Y

#define BAR_WINDOW_OPEN_BOTTOM_X
#define BAR_WINDOW_OPEN_BOTTOM_Y

#define BAR_WINDOW_SELECT_TOP_X
#define BAR_WINDOW_SELECT_TOP_Y

#define BAR_WINDOW_SELECT_MIDDLE_X
#define BAR_WINDOW_SELECT_MIDDLE_Y

#define BAR_WINDOW_SELECT_BOTTOM_X
#define BAR_WINDOW_SELECT_BOTTOM_Y